# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main
  - story/*

pool: Default

steps:
  - task: Npm@1
    inputs:
      command: "install"
      verbose: true
  - task: Npm@1
    inputs:
      command: "run test"
      verbose: true
